app:
  config:
    title: api标题
    description: api描述
    version: 0.0.1
    root_path: "/api" #使用nginx反向代理时设置, "/api"
server:
  host: 0.0.0.0
  port: 8080
  reload: false
cors:
    allow_origins: ['*']
sqlalchemy:
  echo: false
database:
  sqlite:
    auth:
      url: "sqlite:///./databases/auth.sqlite3"
SECRET_KEY: 